imagePullSecret: regcred
server:
  image:
    repository: ghcr.io/tomiwallet/tomi-mpc/server
    pullPolicy: Always
    tag: v0.1
  name: tomi-mpc-server
  enabled: true
  replicas: 1
  resources: {}
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
    host: mpc.stag.tomiwallet.com
    tls:
      enabled: true
      secret: mpc.stag.tomiwallet.com
  env:
    - name: DATABASE_URL
      value: postgresql://mpc:password@tomi-mpc-db-postgresql/mpc
    - name: ENCRYPTION_PUBLIC_KEY
      valueFrom:
        secretKeyRef:
          name: tomi-mpc-keys
          key: public.pem
