name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build . -t ghcr.io/tomiwallet/tomi-mpc/server:${GITHUB_REF/refs\/tags\//}
      - name: Publish
        run: |
          echo "${{ github.token }}" | docker login ghcr.io --username "tomiwallet" --password-stdin
          docker push ghcr.io/tomiwallet/tomi-mpc/server:${GITHUB_REF/refs\/tags\//}
